import {StyleSheet, Text, View} from 'react-native';

const Commonstyles = StyleSheet.create({
  warningText: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '400',
    color: 'red',
    alignSelf: 'center',
    marginTop: 5,
    marginBottom: -5,
  },
  UploadText: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '400',
    color: '#FFFFFF',
    alignSelf: 'center',
    marginTop: 5,
    marginBottom: -5,
  },
  LogoWhite: {
    fontFamily: 'Lexend-ExtraBold',
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  LogoWhite20: {
    fontFamily: 'Lexend-ExtraBold',
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  LogoWhite20500: {
    fontFamily: 'Lexend-ExtraBold',
    fontSize: 20,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  HeadingWhite: {
    fontFamily: 'Lexend-SemiBold',
    fontSize: 28,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  HeadingGrey: {
    fontFamily: 'Lexend-SemiBold',
    fontSize: 28,
    fontWeight: '600',
    color: '#212121',
  },
  TextWhite: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '400',
    color: '#FFFFFF',
  },
  TextWhite24: {
    fontFamily: 'Lexend-Regular',
    fontSize: 24,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  TextWhite24400: {
    fontFamily: 'Lexend-Regular',
    fontSize: 24,
    fontWeight: '400',
    color: '#FFFFFF',
  },
  TextWhite500: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  TextGreen24: {
    fontFamily: 'Lexend-Regular',
    fontSize: 24,
    fontWeight: '700',
    color: '#1DB954',
  },
  TextRed24: {
    fontFamily: 'Lexend-Regular',
    fontSize: 24,
    fontWeight: '700',
    color: '#ED213E',
  },
  TextGreen: {
    fontFamily: 'Lexend-Regular',
    fontSize: 13,
    fontWeight: '500',
    color: '#1DB954',
  },
  TextWhiteProfileUserName: {
    fontFamily: 'Lexend-Bold',
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  TextWhite18600: {
    fontFamily: 'Lexend-Bold',
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  TextWhiteFeatured: {
    fontFamily: 'Lexend-Regular',
    fontSize: 18,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  TextGreyLight: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '300',
    color: '#7E7E7E',
  },
  TextGrey12: {
    fontFamily: 'Lexend-Regular',
    fontSize: 12,
    fontWeight: '400',
    color: '#7E7E7E',
  },
  TextWhite12: {
    fontFamily: 'Lexend-Regular',
    fontSize: 12,
    fontWeight: '400',
    color: '#FFFFFF',
  },
  TextWhite12300: {
    fontFamily: 'Lexend-Regular',
    fontSize: 12,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  TextGrey12300: {
    fontFamily: 'Lexend-Regular',
    fontSize: 12,
    fontWeight: '300',
    color: '#7E7E7E',
  },
  TextGreen12: {
    fontFamily: 'Lexend-Regular',
    fontSize: 12,
    fontWeight: '300',
    color: '#1DB954',
  },
  TextGreen14: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '300',
    color: '#1DB954',
  },
  TextGreen14500: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '500',
    color: '#1DB954',
  },
  TextGrey12Light: {
    fontFamily: 'Lexend-Regular',
    fontSize: 12,
    fontWeight: '300',
    color: '#7E7E7E',
  },
  TextWhiteCalender: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  TextWhiteFeed: {
    fontFamily: 'Lexend-Light',
    fontSize: 15,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  TextgreyFeed15: {
    fontFamily: 'Lexend-Light',
    fontSize: 15,
    fontWeight: '300',
    color: '#7E7E7E',
  },
  TextWhiteUserName: {
    fontFamily: 'Lexend-Light',
    fontSize: 15,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  TextWhiteCalender: {
    fontFamily: 'Lexend-Light',
    fontSize: 15,
    fontWeight: '400',
    color: '#FFFFFF',
  },
  TextWhiteCalenderGreen: {
    fontFamily: 'Lexend-Light',
    fontSize: 15,
    fontWeight: '400',
    color: '#1400DB954',
  },
  TextGreyCalender: {
    fontFamily: 'Lexend-Light',
    fontSize: 15,
    fontWeight: '400',
    color: '#7E7E7E',
  },
  TextWhiteGroupName: {
    fontFamily: 'Lexend-Regular',
    fontSize: 17,
    fontWeight: '400',
    color: '#FFFFFF',
  },
  TextWhiteMembers: {
    fontFamily: 'Lexend-Regular',
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  TextWhiteMembersBold: {
    fontFamily: 'Lexend-Regular',
    fontSize: 26,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  TextWhiteMembersName: {
    fontFamily: 'Lexend-Regular',
    fontSize: 16,
    fontWeight: '400',
    color: '#FFFFFF',
  },
  TextWGreyMembersName: {
    fontFamily: 'Lexend-Regular',
    fontSize: 16,
    fontWeight: '400',
    color: '#7E7E7E',
  },

  TextGrey: {
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    fontWeight: '400',
    color: '#7E7E7E',
  },
  TextGreysmall: {
    fontFamily: 'Lexend-Regular',
    fontSize: 13,
    fontWeight: '400',
    color: '#7E7E7E',
  },
  TextGreysmall300: {
    fontFamily: 'Lexend-Regular',
    fontSize: 13,
    fontWeight: '300',
    color: '#7E7E7E',
  },
  TextGreensmall: {
    fontFamily: 'Lexend-Regular',
    fontSize: 13,
    fontWeight: '400',
    color: '#1DB954',
  },
  TextWhitesmall: {
    fontFamily: 'Lexend-Regular',
    fontSize: 13,
    fontWeight: '400',
    color: '#FFFFFF',
  },
  TextWhitesmall300: {
    fontFamily: 'Lexend-Regular',
    fontSize: 13,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  TextWhitesmallmini: {
    fontFamily: 'Lexend-Regular',
    fontSize: 11,
    fontWeight: '400',
    color: '#FFFFFF',
  },

  TextGreysmallmini: {
    fontFamily: 'Lexend-Regular',
    fontSize: 11,
    fontWeight: '300',
    color: '#7E7E7E',
  },
  TextGreensmallmini: {
    fontFamily: 'Lexend-Regular',
    fontSize: 11,
    fontWeight: '300',
    color: '#1DB954',
  },
  TextWhitesmallmini300: {
    fontFamily: 'Lexend-Regular',
    fontSize: 11,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  TextGreysmallEmail: {
    fontFamily: 'Lexend-Light',
    fontSize: 10,
    fontWeight: '300',
    color: '#7E7E7E',
  },
  TextWhitesmallEmail: {
    fontFamily: 'Lexend-Light',
    fontSize: 10,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  inputText: {
    padding: 18,
    backgroundColor: '#212121',
    borderRadius: 10,
    color: '#FFFFFF',
  },
  inputTextReply: {
    padding: 14,
    backgroundColor: '#212121',
    borderRadius: 10,
    color: '#FFFFFF',
  },
  inputTextBlack: {
    padding: 14,
    backgroundColor: '#121212',
    borderRadius: 10,
    color: '#FFFFFF',
  },
  inputTextForPost: {
    height: 200,
    textAlignVertical: 'top',
    backgroundColor: '#121212',
    borderRadius: 10,
    color: '#FFFFFF',
  },
  ButtonGreen: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 23,
    backgroundColor: '#1DB954',
    borderRadius: 10,
  },
  ButtonBlue: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 23,
    backgroundColor: '#00A3FF',
    borderRadius: 10,
  },
  ButtonGreen2: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    backgroundColor: '#1DB954',
    borderRadius: 10,
  },
  ButtonGrey: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 23,
    backgroundColor: '#7E7E7E',
    borderRadius: 10,
  },
  otherButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderWidth: 2,
    borderColor: '#212A39',
    borderRadius: 10,
  },
  TextInput: {
    padding: 8,
    color: '#FFFFFF',
    backgroundColor: '#121212',
    borderRadius: 8,
  },
});

const Font = {
  green: '#1DB954',
  blue: '#00A3FF',
  blue2: '#3B8CD8',
  red: '#ED213E',
  textFieldColor: '#2F2F2F',
  grey: '#212121',
  grey2: '#1C1C1D',
  darkGrey: '#212A39',
  greyText: '#7E7E7E',
  greyNew: '#262626',
  black: '#121212',
  white: '#FFFFFF',
  fontfamily: 'Lexend-Regular',
  LogoWeight: '800',
  LogoSize: 20,

  HeadingWeight: '600',
  HeadingSize: 28,

  TextWeight: '400',
  TextSize: 14,
};
export {Font, Commonstyles};
